# DigitalOcean App Platform Configuration
# Save as app.yaml in your repository root

name: smarttaxes
services:
- name: web
  source_dir: /
  github:
    repo: your-username/SmartTaxes
    branch: main
  run_command: npm start
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 5000
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "5000"
  - key: DATABASE_URL
    value: ${db.DATABASE_URL}
  - key: SESSION_SECRET
    value: ${SESSION_SECRET}
  - key: JWT_SECRET
    value: ${JWT_SECRET}
  - key: OPENAI_API_KEY
    value: ${OPENAI_API_KEY}
  - key: ANTHROPIC_API_KEY
    value: ${ANTHROPIC_API_KEY}
  - key: STRIPE_SECRET_KEY
    value: ${STRIPE_SECRET_KEY}
  - key: STRIPE_PUBLISHABLE_KEY
    value: ${STRIPE_PUBLISHABLE_KEY}

databases:
- name: db
  engine: PG
  version: "13"
  size: db-s-dev-database
  num_nodes: 1
